# -*- coding: utf-8 -*-
"""AKGEC GEN AI CLASS 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tc03gAwsec4hkHH4RmHJZOmhdMCKUka8
"""

import numpy as np

experience=5
skill_score=8
x=np.array([experience, skill_score])
y=np.array([0.4,0.6])

b=-2

z=np.dot(x,y)+b
print("z=", round(z,2))

relu_output=max(0,z)
print("relu_output=", round(relu_output))

sigmoid_output=1/(1+np.exp(-z))
print("sigmoid output=",round(sigmoid_output,2))

X=np.array([5,8])
W=np.array([0.4,0.6])
b=-2
Z=np.dot(X,W)+b
output=1/(1+np.exp(-Z))
print("input: ",x)
print("weight: ",W)
print("bias: ",b)
print("weighted sum(Z): ",round(Z,2))
print("final output: ",round(output,4))